server:
  port: 8082
  servlet-path: /cxf-test

cxf:
  path: /
  servlet.init: 
    service-list-path: /info
  jaxrs:
    component-scan: true
    classes-scan-packages: org.apache.cxf.jaxrs.swagger, com.fasterxml.jackson.jaxrs.json

spring:
  profiles:
    active:
    - cloud
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
    pool-name: SpringBootHikariCP
    maximum-pool-size: 5
    minimum-idle: 2
    max-lifetime: 2000000
    connection-timeout: 30000
    idle-timeout: 500
    pool-prepared-statements: true
    max-open-prepared-statements: 10
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  path: /logs/cxf.log